---
title: "Exploratory Data Analysis"
author: "Silvia Ventoruzzo"
date: "4/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en")
Sys.setlocale("LC_ALL", "en_US.UTF-8")
```

```{r}
source("01_functions.R")
# p_load(grid)
# p_load(gridExtra)
p_load(ggplot2)
```

## Distribution of price
```{r}
# bp <- boxplot(listings$price)
# bp$out
# 
# 
# ?ggplot(listings, aes(x = price)) +
#     geom_histogram(binwidth=.5, colour="black", fill="light blue") +
#     geom_vline(aes(xintercept=mean(price, na.rm=T)),   # Ignore NA values for mean
#                color="red", linetype="dashed", size=1)
```

# Correlation between different variables and price

```{r}
# Transform categorical variables from rows to column
listings_price <- listings %>%
  recode_all("room_type") %>% from_row_to_col("room_type") %>%
  recode_all("property_type") %>% from_row_to_col("property_type") %>%
  recode_all("cancellation_policy") %>% from_row_to_col("cancellation_policy") %>%
  recode_all("district") %>% from_row_to_col("district") %>%
  recode_all("vbb_area") %>% from_row_to_col("vbb_area") %>%
  recode_all("neighbourhood") %>% from_row_to_col("neighbourhood") %>%
  dplyr::select(-id, -lat, -long, -listing_url)

# Create dataframe with price correlations
listings_price_correlation <- cor(listings_price$price, listings_price) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(corr = V1) %>%
  tibble::rownames_to_column(var = "variable") %>%
  dplyr::filter(variable != "price") %>%
  dplyr::mutate(sign = ifelse(corr > 0, "positive",
                       ifelse(corr < 0, "negative",
                                        "null")))

# LaTeX
p_load(xtable)

listings_price_correlation %>% 
  head(rows = 5) %>% 
  xtable(type = "latex") %>%
  print(include.rownames = FALSE)


# Product vector with colors for y-axis text
# color <-  ifelse(listings_price_correlation$corr > 0, "green4",
#                         ifelse(listings_price_correlation$corr < 0, "red1",
#                                          "blue3"))

# Produce plot
listings_price_correlation %>%
  ggplot(aes(x = variable, y = corr, fill = sign)) +
  geom_bar(stat="identity") +
  scale_fill_manual("sign", values = c("positive" = "green4", "negative" = "red1", "null" = "blue3"),
                    guide=FALSE) +
  coord_flip() +
  labs(title = "Correlation with price") +
  # coord_fixed(ylim = length(unique(listings_price_correlation$variable))) +
  # expand_limits(x = 3*ncol(listings_price_correlation)) +
  theme(axis.text.y = element_text(colour = ifelse(listings_price_correlation$corr > 0, "green4",
                        ifelse(listings_price_correlation$corr < 0, "red1",
                                         "blue3"))),
        plot.title = element_text(hjust = 0.5, size = 17))
```

# Linear regression

```{r}
# Fit linear model
listings_price_lm <- lm(price ~ ., data = listings_price) 

# Extract coefficients and p-values
listings_price_lm_results <- data.frame(
    variable      = names(listings_price_lm$coefficients[!is.na(listings_price_lm$coefficients)]),
    coeff         = listings_price_lm$coefficients[!is.na(listings_price_lm$coefficients)],
    p_value_coeff = summary(listings_price_lm)$coefficients[,4],
    p_value_model = pf(summary(listings_price_lm)$fstatistic[1],
                      summary(listings_price_lm)$fstatistic[2],
                      summary(listings_price_lm)$fstatistic[3],
                      lower.tail=F)) %>%
  mutate_if(is.numeric, function(x) round(x, 4))
```

## Boxplots

Price per district

```{r}
# District vs. Price
# listings %>% 
#   dplyr::group_by(district) %>%
#   dplyr::mutate(median_price_district = median(price)) %>%
#   ungroup() %>%
#   dplyr::mutate(median_price = median(price),
#                 median = ifelse(median_price_district > median_price, "high",
#                          ifelse(median_price_district < median_price, "low",
#                                                                       "average"))) %>%
#   ggplot(aes(x = district, y = price, fill = median)) + 
#   geom_boxplot(outlier.shape = NA) +
#   coord_flip() +
#     scale_fill_manual("median", values = c("low" = "green4", "high" = "red1", "average" = "blue3")) +
#   scale_y_continuous(limits = quantile(listings$price, c(0, 0.95))) +
#   labs(title = "Boxplot of districts with respect to the price",
#        subtitle = "Outliers not displayed") +
#   theme(plot.title = element_text(hjust = 0.5, size = 15),
#         plot.subtitle = element_text(hjust = 0.5, size = 10))
```

Price wrt number of stations and attractions nearby

```{r}
# Number of attractions nearby
# g1 <- listings %>% 
#   dplyr::mutate(attraction_count = as.factor(attraction_count)) %>%
#   ggplot(aes(x = attraction_count, y = price)) + 
#   geom_boxplot(outlier.shape = NA) +
#   scale_y_reverse(limits = quantile(listings$price, c(0.992, 0))) +
#   # scale_fill_manual("median", values = c("low" = "green4", "high" = "red1", "average" = "blue3"),
#   #                   guide=FALSE) +
#   labs(title = "for the number of attractions attractions nearby",
#        subtitle = "Outliers not displayed") +
#   theme(plot.title = element_text(hjust = 0.5, size = 8),
#         plot.subtitle = element_text(hjust = 0.5, size = 6),
#         axis.title.y = element_blank(),
#         axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         plot.margin = unit(c(1,-1,1,0), "mm"))
# gg1 <- g1 %>%
#   ggplot_build() %>%
#   ggplot_gtable()

# Number of stations nearby
# g2 <- listings %>% 
#   dplyr::mutate(station_count = as.factor(station_count)) %>%
#   ggplot(aes(x = station_count, y = price)) + 
#   geom_boxplot(outlier.shape = NA) +
#   # scale_fill_manual("median", values = c("low" = "green4", "high" = "red1", "average" = "blue3"),
#   #                   guide=FALSE) +
#   scale_y_continuous(limits = quantile(listings$price, c(0, 0.992))) +
#   labs(title = "for the number of stations nearby") +
#   theme(plot.title = element_text(hjust = 0.5, size = 8),
#         axis.title.y = element_blank(),
#         axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         plot.margin = unit(c(1,0,1,-1), "mm"))
# gg2 <- g2 %>%
#   ggplot_build() %>%
#   ggplot_gtable()

# Central part - NOT WORKING YET
# listings %>%
#   # dplyr::group_by(cancellation_policy) %>%
#   # summarize(x = 1) %>%
#   # dplyr::mutate(cancellation_policy = recode(as.factor(cancellation_policy),
#   #                                            "strict_14_with_grace_period" = "strict\n14\nwith\ngrace\nperiod",
#   #                                            "super_strict_30" = "super\nstrict\n30",
#   #                                            "super_strict_60" = "super\nstrict\n60")) %>%
#   ggplot(aes(x = 1, y = price)) +
#   # geom_text(aes(label = cancellation_policy), size = 3) +
#   geom_segment(aes(x = 0.94, xend = 0.96, yend = price)) +
#   geom_segment(aes(x = 1.04, xend = 1.065, yend = price)) +
#   labs(title = "") +
#   scale_x_continuous(expand=c(0,0),limits=c(0.94,1.065)) +
#   theme(axis.title=element_blank(),
#         panel.grid=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.background=element_blank(),
#         axis.text.x=element_text(color=NA),
#         axis.ticks.x=element_line(color=NA),
#         plot.margin = unit(c(1,-1,1,-1), "mm"))
# gg.mid <- g.mid %>%
#   ggplot_build() %>%
#   ggplot_gtable()
```

Cancellation policy
From: https://stackoverflow.com/questions/40912966/format-the-y-axis-labels-with-two-lines

```{r}
# Cancellation policy vs. Price
# g1 <- listings %>% 
#   dplyr::group_by(cancellation_policy) %>%
#   dplyr::mutate(median_price_cancellation = median(price)) %>%
#   ungroup() %>%
#   dplyr::mutate(median_price = median(price),
#                 median = ifelse(median_price_cancellation > median_price, "high",
#                          ifelse(median_price_cancellation < median_price, "low",
#                                                                           "average"))) %>%
#   ggplot(aes(x = cancellation_policy, y = price, fill = median)) + 
#   geom_boxplot(outlier.shape = NA) +
#   coord_flip() +
#   scale_y_reverse(limits = quantile(listings$price, c(0.95, 0))) +
#   scale_fill_manual("median", values = c("low" = "green4", "high" = "red1", "average" = "blue3"),
#                     guide=FALSE) +
#   labs(title = "with respect to the price",
#        subtitle = "Outliers not displayed") +
#   theme(plot.title = element_text(hjust = 0.5, size = 8),
#         plot.subtitle = element_text(hjust = 0.5, size = 6),
#         axis.title.y = element_blank(),
#         axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         plot.margin = unit(c(1,-1,1,0), "mm"))
# gg1 <- g1 %>%
#   ggplot_build() %>%
#   ggplot_gtable()
# 
# # Cancellation policy vs. Distance to nearest (top 10) attraction
# g2 <- listings %>% 
#   dplyr::group_by(cancellation_policy) %>%
#   dplyr::mutate(median_attrdist_cancellation = median(attraction_dist)) %>%
#   ungroup() %>%
#   dplyr::mutate(median_attrdist = median(attraction_dist),
#                 median = ifelse(median_attrdist_cancellation > median_attrdist, "high",
#                          ifelse(median_attrdist_cancellation < median_attrdist, "low",
#                                                                           "average"))) %>%
#   ggplot(aes(x = cancellation_policy, y = attraction_dist, fill = median)) + 
#   geom_boxplot(outlier.shape = 1, outlier.stroke = 0.3) +
#   coord_flip() +
#   scale_fill_manual("median", values = c("low" = "green4", "high" = "red1", "average" = "blue3"),
#                     guide=FALSE) +
#   # scale_y_continuous(limits = quantile(listings$price, c(0, 0.95))) +
#   labs(title = "with respect to distance\nto the nearest (top 10) attractions") +
#   theme(plot.title = element_text(hjust = 0.5, size = 8),
#         axis.title.y = element_blank(),
#         axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         plot.margin = unit(c(1,0,1,-1), "mm"))
# gg2 <- g2 %>%
#   ggplot_build() %>%
#   ggplot_gtable()
# 
# # Central part
# g.mid <- listings %>%
#   dplyr::group_by(cancellation_policy) %>%
#   summarize(x = 1) %>%
#   dplyr::mutate(cancellation_policy = recode(as.factor(cancellation_policy),
#                                              "strict_14_with_grace_period" = "strict\n14\nwith\ngrace\nperiod",
#                                              "super_strict_30" = "super\nstrict\n30",
#                                              "super_strict_60" = "super\nstrict\n60")) %>%
#   ggplot(aes(x = x, y = cancellation_policy)) +
#   geom_text(aes(label = cancellation_policy), size = 3) +
#   geom_segment(aes(x = 0.94, xend = 0.96, yend = cancellation_policy)) +
#   geom_segment(aes(x = 1.04, xend = 1.065, yend = cancellation_policy)) +
#   labs(title = "") +
#   scale_x_continuous(expand=c(0,0),limits=c(0.94,1.065)) +
#   theme(axis.title=element_blank(),
#         panel.grid=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.background=element_blank(),
#         axis.text.x=element_text(color=NA),
#         axis.ticks.x=element_line(color=NA),
#         plot.margin = unit(c(1,-1,1,-1), "mm"))
# gg.mid <- g.mid %>%
#   ggplot_build() %>%
#   ggplot_gtable()
# 
# # Join plots
# grid.arrange(gg1, gg.mid, gg2, ncol=3,
#              widths = c(4/9,1/9,4/9),
#              top = textGrob("Boxplots of cancellation policies"))
```

